//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZ.Aisino.IntellEstate.DbEntity
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
    
    
    /// <summary>
    /// 
    /// </summary>
    [Serializable,DataContract]
    public partial class Area
    {
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public int ID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public int ParentID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(50)]
    	public string Name { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public bool IsLock { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(50)]
    	public string GroupName { get; set; }
    
    }
}
