//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZ.Aisino.IntellEstate.DbEntity
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
    
    
    /// <summary>
    /// 
    /// </summary>
    [Serializable,DataContract]
    public partial class BASE_APPLICATION_ROLES
    {
        public BASE_APPLICATION_ROLES()
        {
            this.BASE_APPLICATION_ROLE_RIGHT = new HashSet<BASE_APPLICATION_ROLE_RIGHT>();
            this.BASE_USERROLE = new HashSet<BASE_USERROLE>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public decimal APPLICATION_ROLE_ID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public decimal APPLICATION_ID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string APPLICATION_KEY { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string APPLICATION_CODE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string APPLICATION_NAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public decimal PLATFORM { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public decimal PARENT_ID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string ROLE_NAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(400)]
    	public string ROLE_RESTRICTION { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(400)]
    	public string ROLE_REMARK { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember]
    	public decimal? APPLAY_TO { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public decimal SEQUENCE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(200)]
    	public string SEQUENCE_STRING { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public decimal DELETE_MARK { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string MODIFY_USERNAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string MODIFY_FULLNAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public System.DateTime MODIFY_DATE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string CREATE_USERNAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string CREATE_FULLNAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public System.DateTime CREATE_DATE { get; set; }
    
    
        public virtual ICollection<BASE_APPLICATION_ROLE_RIGHT> BASE_APPLICATION_ROLE_RIGHT { get; set; }
        public virtual ICollection<BASE_USERROLE> BASE_USERROLE { get; set; }
    }
}
