//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZ.Aisino.IntellEstate.DbEntity
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
    
    
    /// <summary>
    /// 
    /// </summary>
    [Serializable,DataContract]
    public partial class BASE_APPLICATIONS
    {
        public BASE_APPLICATIONS()
        {
            this.BASE_MODULE = new HashSet<BASE_MODULE>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public decimal APPLICATION_ID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string APPLICATION_KEY { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string APPLICATION_CODE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string APPLICATION_NAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(508)]
    	public string ICON { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(1000)]
    	public string DESCRIPTION { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(100)]
    	public string URL { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(80)]
    	public string IP { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember]
    	public decimal? BINDING { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember]
    	public decimal? SEQUENCE { get; set; }
    
    
        public virtual ICollection<BASE_MODULE> BASE_MODULE { get; set; }
    }
}
