//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZ.Aisino.IntellEstate.DbEntity
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
    
    
    /// <summary>
    /// 
    /// </summary>
    [Serializable,DataContract]
    public partial class BASE_MODULE
    {
        public BASE_MODULE()
        {
            this.BASE_MODULE_BUTTON = new HashSet<BASE_MODULE_BUTTON>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public decimal MODULE_ID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public decimal APPLICATION_ID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string APPLICATION_CODE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string APPLICATION_NAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember]
    	public decimal? PLATFORM { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public decimal PARENT_ID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(600)]
    	public string MODULE_CODE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string MODULE_NAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public decimal MODULE_TYPE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(400)]
    	public string MODULE_RIGHT_CODE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(600)]
    	public string NAVIGATE_URL { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(600)]
    	public string QUERY_STRING { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(600)]
    	public string DIRECTORY { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(600)]
    	public string FILENAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(508)]
    	public string ICON { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(508)]
    	public string IMG { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember]
    	public decimal? MODULE_LAYER { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(100)]
    	public string VERSION { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(1000)]
    	public string INFORMATION { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(4000)]
    	public string REMARK { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public decimal SEQUENCE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(1000)]
    	public string SEQUENCE_STRING { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public decimal DELETE_MARK { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string MODIFY_USERNAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string MODIFY_FULLNAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public System.DateTime MODIFY_DATE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string CREATE_USERNAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required, StringLength(100)]
    	public string CREATE_FULLNAME { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public System.DateTime CREATE_DATE { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember]
    	public decimal? BUTTON_ID { get; set; }
    
    
        public virtual BASE_APPLICATIONS BASE_APPLICATIONS { get; set; }
        public virtual ICollection<BASE_MODULE_BUTTON> BASE_MODULE_BUTTON { get; set; }
    }
}
