//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZ.Aisino.IntellEstate.DbEntity
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
    
    
    /// <summary>
    /// 
    /// </summary>
    [Serializable,DataContract]
    public partial class Poster
    {
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public int PosterID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember]
    	public int? ExhibitionID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember]
    	public int? InfoID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember]
    	public int? HallID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember]
    	public int? MuseumID { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember , Required]
    	public byte Category { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(1000)]
    	public string OriginDir { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(100)]
    	public string Filename { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(1000)]
    	public string OriginPath { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember, StringLength(1000)]
    	public string RootPath { get; set; }
    
        /// <summary>
        /// 
        /// </summary>
        [DataMember]
    	public int? Sequence { get; set; }
    
    }
}
