//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZ.Aisino.IntellEstate.DbContext.Platform
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using SZ.Aisino.EstateModel.DbEntity;
    
    public partial class EstateModelContainer : DbContext
    {
        public EstateModelContainer()
            : base("name=EstateModelContainer")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
     
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Company> Companies { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Base_Location> Base_Locations { get; set; }
        public DbSet<Payment_Order> Payment_Orders { get; set; }
        public DbSet<Payment_Order_Detail> Payment_Order_Details { get; set; }
        public DbSet<Business> Business { get; set; }
        public DbSet<Currency_By_Company> Currency_By_CompanySet { get; set; }
        public DbSet<Currency_Rate> Currency_Rate { get; set; }
        public DbSet<Customer_Contact> Customer_Contacts { get; set; }
        public DbSet<Logger> Loggers { get; set; }
        public DbSet<Soap_Backup> Soap_Backups { get; set; }
        public DbSet<Payment_Order_Trace> Payment_Order_TraceSet { get; set; }
        public DbSet<Company_Contact> Company_ContactSet { get; set; }
        public DbSet<Company_Contract> Company_Contracts { get; set; }
        public DbSet<Fee_Type> Fee_Types { get; set; }
        public DbSet<Company_Fee> Fee { get; set; }
        public DbSet<Customer_Fee> Customer_Fees { get; set; }
        public DbSet<Company_Fee_Detail> Company_Fee_Detais { get; set; }
    }
}
