//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZ.Aisino.IntellEstate.DbContext.UC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using SZ.Aisino.UC.DbEntity;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
            this.Configuration.ProxyCreationEnabled = false;
            this.Configuration.LazyLoadingEnabled = false;
        }
     
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BASE_APPLICATION_ROLE_RIGHT> BASE_APPLICATION_ROLE_RIGHT { get; set; }
        public DbSet<BASE_APPLICATION_ROLES> BASE_APPLICATION_ROLES { get; set; }
        public DbSet<BASE_APPLICATIONS> BASE_APPLICATIONS { get; set; }
        public DbSet<BASE_BUTTON> BASE_BUTTON { get; set; }
        public DbSet<BASE_MODULE> BASE_MODULE { get; set; }
        public DbSet<BASE_MODULE_BUTTON> BASE_MODULE_BUTTON { get; set; }
        public DbSet<BASE_USERINFO> BASE_USERINFO { get; set; }
        public DbSet<BASE_USERROLE> BASE_USERROLE { get; set; }
        public DbSet<Area> Areas { get; set; }
        public DbSet<Poster> Posters { get; set; }
    }
}
